site_name: 研究室ポータル
site_url: https://motofumi-fushimi.github.io/hub/
repo_url: https://github.com/motofumi-fushimi/hub

docs_dir: docs
site_dir: site

# UIテーマ設定
theme:
  name: material
  language: ja
  features:
    - navigation.tabs        # 上部にタブメニューを表示
    - navigation.top         # 「トップに戻る」ボタン
    - navigation.sections      # 第2階層以下のフォルダを「セクション（太字の区切り）」として表示
    - toc.follow               # 右目次の追従
  palette:
    - scheme: default
  icon:
    logo: material/account-circle # 将来的に適当なロゴで置き換える

# 著作権表示
copyright: © 2026 Motofumi Fushimi # Fushimi Lab, *** University

# クレジット表示を消す（ライセンス条項に反しない）
extra:
  generator: false

# MkDocs全体に適用するCSS
extra_css:
  - Assets/Styles/website.css

# 階層構造を自動処理するためのプラグイン
plugins:
  - search
  - tags:
      tags_file: tags.md
  - awesome-pages            # ディレクトリ構造＝メニュー構造にする
  - exclude:
      glob:
        - ".git/**/*"        # Gitフォルダを除外
        - ".vscode/**/*"     # VSCode設定を除外
        - ".github/**/*"     # GitHub設定を除外
        - ".gitignore"       # 設定ファイルは出さない
        - "Local/**/*"       # ローカルのドラフトフォルダを除外
        - "mkdocs.yml"       # 自分自身を除外
        - "readme.md"        # GitHub用の説明はサイトに出さない

# Markdownの拡張機能（必要に応じて）
markdown_extensions:
  - admonition               # note, warningなどの警告表示
  - pymdownx.superfences     # コードブロックの強化
  - attr_list                # 画像サイズ調整など
